const map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([31.95,5.33],7);L.control.zoom({position:'bottomright'}).addTo(map);
const osm=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});const sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});osm.addTo(map);
const $=id=>document.getElementById(id);let userMarker,accuracy,watch=null,last=null,track=[],trackLine=L.polyline([],{weight:4}).addTo(map),recording=false,trackStart=null;let overlays={wells:L.layerGroup().addTo(map),hazards:L.layerGroup().addTo(map),places:L.layerGroup().addTo(map)};
function toast(t){$('toast').innerHTML='<span class="toast">'+t+'</span>';setTimeout(()=>$('toast').innerHTML='',3000)}function panel(title,html){$('panel').innerHTML='<h2>'+title+'</h2>'+html+'<button onclick="closePanel()">إغلاق</button>';$('panel').classList.remove('hidden')}function closePanel(){$('panel').classList.add('hidden')}window.closePanel=closePanel;
function startGPS(){if(!navigator.geolocation)return toast('GPS غير مدعوم');$('gps').textContent='📍 GPS — جاري التحديد…';watch=navigator.geolocation.watchPosition(p=>{const c=p.coords;last={lat:c.latitude,lon:c.longitude,acc:c.accuracy,speed:c.speed||0,heading:c.heading};$('gps').textContent='📍 '+c.latitude.toFixed(5)+', '+c.longitude.toFixed(5);$('speed').textContent='🚙 '+((c.speed||0)*3.6).toFixed(1)+' km/h';if(c.heading!=null)$('nav').textContent='🧭 '+Math.round(c.heading)+'°';const ll=[c.latitude,c.longitude];if(!userMarker)userMarker=L.circleMarker(ll,{radius:8,weight:3}).addTo(map).bindPopup('📍 موقعك الحالي');else userMarker.setLatLng(ll);if(!accuracy)accuracy=L.circle(ll,{radius:c.accuracy,weight:1}).addTo(map);else{accuracy.setLatLng(ll);accuracy.setRadius(c.accuracy)}if(recording){track.push({lat:c.latitude,lon:c.longitude,t:Date.now()});trackLine.setLatLngs(track.map(x=>[x.lat,x.lon]))}},e=>{$('gps').textContent='⚠️ GPS — '+e.message},{enableHighAccuracy:true,maximumAge:2000,timeout:15000})}startGPS();
$('loc').onclick=()=>{if(last)map.setView([last.lat,last.lon],15);else toast('انتظر GPS')};$('mapMode').onclick=()=>{if(map.hasLayer(osm)){map.removeLayer(osm);sat.addTo(map)}else{map.removeLayer(sat);osm.addTo(map)}};$('full').onclick=()=>document.documentElement.requestFullscreen?.();
async function search(q){const u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&countrycodes=dz&accept-language=ar&q='+encodeURIComponent(q);try{return await (await fetch(u)).json()}catch{return[]}}$('go').onclick=async()=>{const q=$('q').value.trim();if(!q)return;const r=await search(q);if(!r.length)return panel('البحث','<div class="row">لم نجد نتيجة. جرّب اسمًا مختلفًا.</div>');map.setView([+r[0].lat,+r[0].lon],14);L.marker([+r[0].lat,+r[0].lon]).addTo(map).bindPopup(r[0].display_name).openPopup();panel('نتيجة البحث',r.slice(0,6).map(x=>`<div class="row">${x.display_name}<br><small>${x.lat}, ${x.lon}</small></div>`).join(''))};$('q').onkeydown=e=>{if(e.key==='Enter')$('go').click()};
async function overpass(query){const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const ep of endpoints){try{const r=await fetch(ep,{method:'POST',body:new URLSearchParams({data:query})});if(r.ok)return await r.json()}catch{}}throw Error('Overpass unavailable')}
async function loadWells(){overlays.wells.clearLayers();toast('جاري تحميل الآبار المسجلة في OpenStreetMap…');const q='[out:json][timeout:35];area["ISO3166-1"="DZ"]->.a;(nwr["man_made"="water_well"](area.a);nwr["amenity"="drinking_water"](area.a););out center tags;';try{const d=await overpass(q);let n=0;d.elements.forEach(x=>{const lat=x.lat??x.center?.lat,lon=x.lon??x.center?.lon;if(lat==null)return;const name=x.tags?.name||'نقطة مياه مسجلة';L.marker([lat,lon]).bindPopup(`<b>💧 ${name}</b><br>المصدر: OpenStreetMap<br>الثقة: 🟡 تحتاج تحقق ميداني<br>الإحداثيات: ${lat.toFixed(6)}, ${lon.toFixed(6)}`).addTo(overlays.wells);n++});panel('💧 المياه والآبار',`<div class="row">تم تحميل <b>${n}</b> نقطة مسجلة في OpenStreetMap.</div><div class="row danger">هذه البيانات لا تعني أن الماء موجود حاليًا أو صالح للشرب. يجب التحقق ميدانيًا.</div>`)}catch{panel('💧 المياه','<div class="row">تعذر الاتصال بمصدر البيانات الآن.</div>')}}
async function loadPlaces(){overlays.places.clearLayers();const q='[out:json][timeout:35];area["ISO3166-1"="DZ"]->.a;nwr["amenity"~"fuel|hospital|police|fire_station"](area.a);out center tags;';try{const d=await overpass(q);let n=0;d.elements.forEach(x=>{const lat=x.lat??x.center?.lat,lon=x.lon??x.center?.lon;if(lat==null)return;const t=x.tags||{},name=t.name||t.amenity;L.circleMarker([lat,lon],{radius:6,weight:2}).bindPopup(`🏕️ ${name}<br>المصدر: OpenStreetMap`).addTo(overlays.places);n++});panel('🏕️ الخدمات',`<div class="row">تم تحميل ${n} خدمة مسجلة من OpenStreetMap.</div>`)}catch{panel('🏕️ الخدمات','<div class="row">تعذر تحميل الخدمات الآن.</div>')}}
function hazards(){panel('⚠️ المخاطر','<div class="row danger">لا نعرض مخاطر مخترعة.</div><div class="row">سيتم لاحقًا ربط طبقة المخاطر بقاعدة بيانات موثقة: المصدر + التاريخ + نوع الخطر + درجة الثقة.</div>')}
function savePoint(){if(!last)return toast('فعّل GPS أولًا');const name=prompt('اسم النقطة');if(!name)return;const a=JSON.parse(localStorage.points||'[]');a.push({name,lat:last.lat,lon:last.lon,date:new Date().toISOString()});localStorage.points=JSON.stringify(a);L.marker([last.lat,last.lon]).addTo(map).bindPopup('📌 '+name);toast('تم حفظ النقطة محليًا')}
function saved(){const a=JSON.parse(localStorage.points||'[]');panel('📌 نقاطي',a.length?a.map((x,i)=>`<div class="row"><b>${x.name}</b><br>${x.lat.toFixed(6)}, ${x.lon.toFixed(6)}<br><small>${new Date(x.date).toLocaleString('ar-DZ')}</small></div>`).join(''):'<div class="row">لا توجد نقاط محفوظة.</div>')}
function trip(){if(!recording){recording=true;track=[];trackLine.setLatLngs([]);trackStart=Date.now();panel('🚙 تسجيل الرحلة','<div class="row ok">بدأ تسجيل الرحلة. لا تغلق الصفحة.</div>');}else{recording=false;const distance=track.reduce((s,p,i)=>i?s+map.distance([track[i-1].lat,track[i-1].lon],[p.lat,p.lon]):0,0);localStorage.lastTrip=JSON.stringify({track,start:trackStart,end:Date.now(),distance});panel('🚙 الرحلة محفوظة',`<div class="row">المسافة: <b>${(distance/1000).toFixed(2)} كم</b></div><div class="row">النقاط: ${track.length}</div>`);}}
function sos(){if(!last)return toast('GPS غير جاهز');const msg=`🚨 SAHARA GUIDE DZ SOS\nأحتاج مساعدة.\nالموقع: ${last.lat.toFixed(6)}, ${last.lon.toFixed(6)}\nhttps://maps.google.com/?q=${last.lat},${last.lon}`;if(navigator.share)navigator.share({title:'SOS',text:msg});else navigator.clipboard?.writeText(msg).then(()=>toast('تم نسخ رسالة SOS'))}
function settings(){panel('⚙️ الإعدادات','<div class="row">نسخة التطبيق: <b>PRO V1</b></div><div class="row">الخرائط: OpenStreetMap</div><div class="row">صور الأقمار: Esri World Imagery</div><div class="row">البيانات الميدانية لا تُعتبر مؤكدة إلا مع مصدر وتاريخ تحقق.</div>')}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>({wells:loadWells,roads:()=>panel('🛣️ الطرق','<div class="row">الطرق والأسماء تظهر مباشرة من خريطة OpenStreetMap. الملاحة الصحراوية المتقدمة ستُضاف بعد تجهيز محرك التوجيه وبيانات المسالك.</div>'),hazards,trip,saved,sos,places:loadPlaces,settings}[b.dataset.open])());$('menuBtn').onclick=()=>panel('SAHARA GUIDE DZ PRO','<div class="row">الخريطة هي الواجهة الرئيسية.</div><div class="row">استخدم 💧 للآبار المسجلة، 🏕️ للخدمات، 🚙 لتسجيل الرحلة، و🚨 للطوارئ.</div>');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
