const map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([31.95,5.33],7);L.control.zoom({position:'bottomright'}).addTo(map);
const osm=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});const sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});osm.addTo(map);
document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{document.querySelectorAll('.layer').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.layer==='sat'){map.removeLayer(osm);sat.addTo(map)}else{map.removeLayer(sat);osm.addTo(map)}});
let userMarker=null,accuracyCircle=null,lastPos=null,watchId=null;const gpsStatus=document.getElementById('gpsStatus'),coords=document.getElementById('coords');
function locate(){if(!navigator.geolocation){gpsStatus.textContent='📍 GPS غير مدعوم';return}gpsStatus.textContent='📍 جاري تحديد الموقع...';if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(pos=>{const{latitude,longitude,accuracy}=pos.coords;lastPos=[latitude,longitude];coords.textContent=`${latitude.toFixed(6)}, ${longitude.toFixed(6)}`;gpsStatus.textContent=`📍 GPS ±${Math.round(accuracy)}م`;if(!userMarker)userMarker=L.marker(lastPos,{title:'أنت هنا'}).addTo(map).bindPopup('📍 موقعك الحالي');else userMarker.setLatLng(lastPos);if(!accuracyCircle)accuracyCircle=L.circle(lastPos,{radius:accuracy,weight:1}).addTo(map);else{accuracyCircle.setLatLng(lastPos);accuracyCircle.setRadius(accuracy)}},err=>gpsStatus.textContent='⚠️ GPS: '+err.message,{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}document.getElementById('locateBtn').onclick=()=>{locate();if(lastPos)map.setView(lastPos,15)};locate();
async function geocode(q){try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&accept-language=ar&countrycodes=dz&q='+encodeURIComponent(q));return await r.json()}catch(e){return[]}}
document.getElementById('searchBtn').onclick=async()=>{const q=document.getElementById('search').value.trim();if(!q)return;const results=await geocode(q),p=document.getElementById('panel');if(!results.length){showInfo('🔎 البحث','لم نجد المكان.');return}const x=results[0],ll=[+x.lat,+x.lon];map.setView(ll,15);L.marker(ll).addTo(map).bindPopup('🔎 '+x.display_name).openPopup();showInfo('🔎 نتيجة البحث',`${x.display_name}<br><small>${x.lat}, ${x.lon}</small>`)};document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('searchBtn').click()});
function closePanel(){document.getElementById('panel').classList.add('hidden')}window.closePanel=closePanel;function showInfo(title,body){const p=document.getElementById('panel');p.innerHTML=`<h3>${title}</h3><div>${body}</div><button onclick="closePanel()">إغلاق</button>`;p.classList.remove('hidden')}
document.getElementById('savePoint').onclick=()=>{if(!lastPos){alert('فعّل GPS أولًا');return}const name=prompt('اسم النقطة:','نقطة محفوظة');if(!name)return;const points=JSON.parse(localStorage.getItem('sahara_points')||'[]');points.push({name,lat:lastPos[0],lon:lastPos[1],date:new Date().toISOString()});localStorage.setItem('sahara_points',JSON.stringify(points));L.marker(lastPos).addTo(map).bindPopup('📌 '+name).openPopup()};
document.getElementById('water').onclick=()=>showInfo('💧 المياه','لا توجد آبار وهمية. ستُضاف نقاط المياه فقط مع المصدر وتاريخ التحقق ودرجة الثقة.');document.getElementById('danger').onclick=()=>showInfo('⚠️ المخاطر','لا توجد تحذيرات مختلقة. ستُضاف المخاطر مع المصدر والتاريخ ودرجة الثقة.');document.getElementById('places').onclick=()=>showInfo('🏜️ الأماكن','استخدم البحث للوصول إلى الأماكن المسجلة في OpenStreetMap.');document.getElementById('compass').onclick=()=>showInfo('🧭 البوصلة','أساس البوصلة جاهز؛ تحسين المعايرة وحساسات الاتجاه سيكون ضمن المرحلة التالية.');
document.getElementById('distance').onclick=()=>{if(!lastPos){alert('فعّل GPS أولًا');return}const b=map.getCenter(),d=map.distance(lastPos,b);showInfo('📏 المسافة',`من موقعك إلى مركز الخريطة: <b>${(d/1000).toFixed(2)} كم</b><br>${b.lat.toFixed(6)}, ${b.lng.toFixed(6)}`)};document.getElementById('trip').onclick=()=>showInfo('🚙 الرحلة','تسجيل المسار والسرعة والوقت والمسافة سيكون في المرحلة التالية.');
document.getElementById('sos').onclick=()=>{if(!lastPos){alert('فعّل GPS أولًا');return}const text=`🚨 SOS - أحتاج مساعدة. موقعي: ${lastPos[0].toFixed(6)}, ${lastPos[1].toFixed(6)}\nhttps://maps.google.com/?q=${lastPos[0]},${lastPos[1]}`;if(navigator.share)navigator.share({title:'SAHARA GUIDE DZ - SOS',text});else if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>alert('تم نسخ رسالة SOS مع الموقع'));};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
